name: sefi
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - scanpy
  - squidpy
  - anndata
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - ipykernel